name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      id: gitsemanticversion
      with:
        tag_prefix: "v"
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-rc${increment}"
            
    - name: "Docker login"
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.gitsemanticversion.outputs.version }}
      run: |
        echo "Inicio docker login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin docker login"
        echo "$NEW_VERSION"
        
    # - name: "Docker build image"
    #   run: |
    #     docker build -t wechavez14/graphql-actions:0.0.2 .
    #     docker build -t wechavez14/graphql-actions:latest .
    # - name: "Docker push image"
    #   run: |
    #     docker push wechavez14/graphql-actions:0.0.2
    #     docker push wechavez14/graphql-actions:latest
